---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: apache-ns
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-service
            port:
              number: 443
              
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-ns
  labels:
    run: apache
spec:
  ports:
    - name: apache-port
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app:  apache
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apache-ns
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - protocol: TCP
          containerPort: 443
